services:
  - type: web
    name: howell-asociados
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - src: /static/(.*)
        dest: /static/$1
      - src: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|webp))
        dest: /$1
      - src: /(.*)  # Esta l√≠nea es crucial configura Render para que todas las rutas sirvan a index.html, permitiendo que BrowserRouter maneje el routing.
        dest: /index.html