  services:
  - type: web
    name: howell-asociados
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      # 1. Assets estáticos 
      - src: /static/(.*)
        dest: /static/$1
        headers:
          Cache-Control: public, max-age=31536000
      - src: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|webp))
        dest: /$1
        headers:
          Cache-Control: public, max-age=31536000
      
      # 2. HTML principal
      - src: /index.html
        dest: /index.html
        headers:
          Cache-Control: no-cache
      
      # 3. SPA fallback
      - src: /(.*) # Esta línea es crucial configura Render para que todas las rutas sirvan a index.html, permitiendo que BrowserRouter maneje el routing.
        dest: /index.html
        headers:
          Cache-Control: no-cache